// <auto-generated />
using System;
using IBshopDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBshopDemo.Migrations
{
    [DbContext(typeof(TestHadadianContext))]
    partial class TestHadadianContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IBshopDemo.Models.ArtMonthlyReport", b =>
                {
                    b.Property<int>("ArtMonthlyReportId")
                        .HasColumnType("int");

                    b.Property<int>("AppliedMotionAvgTime")
                        .HasColumnType("int")
                        .HasColumnName("AppliedMotionAVgTime");

                    b.Property<int>("ArchiveDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("ArchivedmotionQty")
                        .HasColumnType("int");

                    b.Property<int>("BannerDesignQty")
                        .HasColumnType("int")
                        .HasColumnName("BannerDesignQTY");

                    b.Property<int>("BrochureDesignAvgTime")
                        .HasColumnType("int")
                        .HasColumnName("brochureDesignAvgTime");

                    b.Property<int>("BrochureDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("CompStudy")
                        .HasColumnType("int");

                    b.Property<int>("GifDesignAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("GifDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("MediaFailureQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MotionQty")
                        .HasColumnType("int")
                        .HasColumnName("MotionQTY");

                    b.Property<int>("MrkReq")
                        .HasColumnType("int");

                    b.Property<int>("NarrationEditQty")
                        .HasColumnType("int");

                    b.Property<int>("RecordedQty")
                        .HasColumnType("int");

                    b.Property<int>("RecordedvideoQty")
                        .HasColumnType("int");

                    b.Property<int>("SiteBannerAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("StandDesigQty")
                        .HasColumnType("int");

                    b.Property<int>("StandDesignAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("StoryDesignAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("StoryDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("VideoArchiveQty")
                        .HasColumnType("int");

                    b.Property<int>("VideoProduceAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ArtMonthlyReportId");

                    b.ToTable("Art Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchKpi", b =>
                {
                    b.Property<string>("KpibranchCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("KPIBranchCode")
                        .IsFixedLength();

                    b.Property<string>("BranchCap")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("branchCap")
                        .IsFixedLength();

                    b.Property<string>("BrcClient")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("BrcCnf")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("BrnReqQty")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("ClienttoIssue")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("ConIntMonPercentage")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Kllevel")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MrkSpv")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NewUser")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PurchaseAvgTime")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("WrongIssue")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("WrongQty")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("WrsupReq")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("WRSupReq")
                        .IsFixedLength();

                    b.HasKey("KpibranchCode");

                    b.ToTable("BranchKPI", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchManagerMonthlyReport", b =>
                {
                    b.Property<int>("BranchManagerMonthlyReportIdBranchManagerMonthlyReportId")
                        .HasColumnType("int")
                        .HasColumnName("BranchManagerMonthlyReportId]\r\nBranchManagerMonthlyReportId");

                    b.Property<int>("AssuranceMrkmtgqty")
                        .HasColumnType("int")
                        .HasColumnName("AssuranceMRKMTGQty");

                    b.Property<int>("AssuranceSuccessMtgqty")
                        .HasColumnType("int")
                        .HasColumnName("AssuranceSuccessMTGQty");

                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ComplainantQty")
                        .HasColumnType("int");

                    b.Property<int>("Conciliation")
                        .HasColumnType("int");

                    b.Property<int>("CoursesMrkmtgfirstAgreementQty")
                        .HasColumnType("int")
                        .HasColumnName("CoursesMRKMTGFirstAgreementQty");

                    b.Property<int>("CoursesMrkmtgqty")
                        .HasColumnType("int")
                        .HasColumnName("CoursesMRKMTGQty");

                    b.Property<int>("CoursesReq")
                        .HasColumnType("int");

                    b.Property<int>("DebtSharesMrkmtgqty")
                        .HasColumnType("int")
                        .HasColumnName("DebtSharesMRKMTGQty");

                    b.Property<int>("DebtSharesSuccessMtgqty")
                        .HasColumnType("int")
                        .HasColumnName("DebtSharesSuccessMTGQty");

                    b.Property<int>("IBcardMrkmtgqty")
                        .HasColumnType("int")
                        .HasColumnName("iBcardMRKMTGQty");

                    b.Property<int>("IBcardSuccessMtgqty")
                        .HasColumnType("int")
                        .HasColumnName("iBcardSuccessMTGQty");

                    b.Property<int>("IBcrowdMrkmtgqty")
                        .HasColumnType("int")
                        .HasColumnName("iBcrowdMRKMTGQty");

                    b.Property<int>("IBcrowdSuccessMtgqty")
                        .HasColumnType("int")
                        .HasColumnName("iBcrowdSuccessMTGQty");

                    b.Property<int>("InvesmentSuccessMtgqty")
                        .HasColumnType("int")
                        .HasColumnName("InvesmentSuccessMTGQty");

                    b.Property<int>("InvestmentMrkmtgqty")
                        .HasColumnType("int")
                        .HasColumnName("InvestmentMRKMTGQty");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BranchManagerMonthlyReportIdBranchManagerMonthlyReportId");

                    b.ToTable("Branch Manager Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Andokhtehrank")
                        .HasColumnType("int");

                    b.Property<int?>("Bimehrank")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchID");

                    b.Property<int?>("BranchRankingId")
                        .HasColumnType("int")
                        .HasColumnName("BranchRankingID");

                    b.Property<int?>("GanjinehRank")
                        .HasColumnType("int");

                    b.Property<int?>("IBcrowdrank")
                        .HasColumnType("int")
                        .HasColumnName("iBcrowdrank");

                    b.Property<int?>("Productrank")
                        .HasColumnType("int");

                    b.Property<int?>("Sandoghrank")
                        .HasColumnType("int");

                    b.Property<int?>("SatisfactionRank")
                        .HasColumnType("int");

                    b.Property<int?>("ServatRank")
                        .HasColumnType("int");

                    b.Property<int?>("Servicerank")
                        .HasColumnType("int")
                        .HasColumnName("servicerank");

                    b.Property<int?>("TotalRank")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BranchRa__3213E83F7329D2F5");

                    b.ToTable("BranchRanking", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchesInfo", b =>
                {
                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchManager")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BranchCode");

                    b.ToTable("Branches Info", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchesMonthlyReport", b =>
                {
                    b.Property<int>("BranchMonthlyReportId")
                        .HasColumnType("int");

                    b.Property<int>("AccBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchCompCheckedQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchCompQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchInfractionQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchMonQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchReformQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchTickects")
                        .HasColumnType("int");

                    b.Property<int>("BranchpersonnelQty")
                        .HasColumnType("int");

                    b.Property<int>("CandstoDevelopmentQty")
                        .HasColumnType("int");

                    b.Property<int>("CoursesNeedQty")
                        .HasColumnType("int");

                    b.Property<int>("CoursesQty")
                        .HasColumnType("int");

                    b.Property<int>("CrttoCusQty")
                        .HasColumnType("int")
                        .HasColumnName("CRTToCusQty");

                    b.Property<int>("FacilityReqQty")
                        .HasColumnType("int");

                    b.Property<int>("FundSettlementQty")
                        .HasColumnType("int");

                    b.Property<int>("FundsConflictsQty")
                        .HasColumnType("int");

                    b.Property<int>("IBcrowdKpiconflictQty")
                        .HasColumnType("int")
                        .HasColumnName("iBcrowdKPIconflictQty");

                    b.Property<int>("IbcardConflictBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcrowdConflictBranchQty")
                        .HasColumnType("int")
                        .HasColumnName("ibcrowdConflictBranchQty");

                    b.Property<int>("InpersonBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("InvestmentCapitalConflicts")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MrkpacTobranchQty")
                        .HasColumnType("int")
                        .HasColumnName("MRKPacTOBranchQty");

                    b.Property<int>("OnlineExamsQty")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelAdReqQty")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelAssuranceReqQty")
                        .HasColumnType("int");

                    b.Property<int>("ReportsConflictsToBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("SendtoBranch")
                        .HasColumnType("int");

                    b.Property<int>("ServicesToBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("SwsolvedQty")
                        .HasColumnType("int")
                        .HasColumnName("SWSolvedQty");

                    b.Property<int>("TicketConflictsQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BranchMonthlyReportId")
                        .HasName("PK_CRM Monthly Report");

                    b.ToTable("Branches Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.CrmMonthlyReport", b =>
                {
                    b.Property<int>("Crmmrid")
                        .HasColumnType("int")
                        .HasColumnName("CRMMRId");

                    b.Property<int>("AndookhtehIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("AndookhtehIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("AndookhtehicketQty")
                        .HasColumnType("int");

                    b.Property<double>("AvgCallDuration")
                        .HasColumnType("float");

                    b.Property<double>("AvgCallWaitingDuration")
                        .HasColumnType("float");

                    b.Property<int>("BranchComplTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("CrmcoursesQty")
                        .HasColumnType("int")
                        .HasColumnName("CRMcoursesQty");

                    b.Property<int>("GanjinehIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("GanjinehIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("GanjinehTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("GoharTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("GoharandServatIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("GoharandServatIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("IbCardTicketQty")
                        .HasColumnType("int")
                        .HasColumnName("ibCardTicketQty");

                    b.Property<int>("IbCrowdTicketQty")
                        .HasColumnType("int")
                        .HasColumnName("ibCrowdTicketQty");

                    b.Property<int>("InCallQty")
                        .HasColumnType("int");

                    b.Property<int>("InChatQty")
                        .HasColumnType("int");

                    b.Property<int>("InCompCallQty")
                        .HasColumnType("int");

                    b.Property<int>("InSurveyCallQty")
                        .HasColumnType("int");

                    b.Property<int>("InVmQty")
                        .HasColumnType("int");

                    b.Property<int>("Inticket")
                        .HasColumnType("int")
                        .HasColumnName("INTicket");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("OnlineChatsurveyQty")
                        .HasColumnType("int");

                    b.Property<int>("OutAccNumEditQty")
                        .HasColumnType("int");

                    b.Property<int>("OutComTrtQty")
                        .HasColumnType("int");

                    b.Property<int>("OutSurveyCallQty")
                        .HasColumnType("int");

                    b.Property<int>("OutVmQty")
                        .HasColumnType("int");

                    b.Property<int>("OutsurveyQty")
                        .HasColumnType("int");

                    b.Property<int>("SejamQty")
                        .HasColumnType("int");

                    b.Property<int>("ServatafarinanTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("SurveyTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("TicketOnlineQty")
                        .HasColumnType("int");

                    b.Property<double>("ToalCallDuration")
                        .HasColumnType("float");

                    b.Property<int>("TotalIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("TotalIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Crmmrid");

                    b.ToTable("CRM Monthly Reports", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.FinancialMonthlyReport", b =>
                {
                    b.Property<int>("FinancialMrid")
                        .HasColumnType("int")
                        .HasColumnName("FinancialMRId");

                    b.Property<int>("CheckedfundQty")
                        .HasColumnType("int");

                    b.Property<int>("ColPrpQty")
                        .HasColumnType("int");

                    b.Property<int>("ContQty")
                        .HasColumnType("int");

                    b.Property<int>("LblPrpQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MtnprpQty")
                        .HasColumnType("int")
                        .HasColumnName("MTNPrpQty");

                    b.Property<int>("PersonnelSetQty")
                        .HasColumnType("int");

                    b.Property<int>("PrpReqQty")
                        .HasColumnType("int");

                    b.Property<int>("Recivedgaurantee")
                        .HasColumnType("int");

                    b.Property<int>("ResFundInstallmenQty")
                        .HasColumnType("int");

                    b.Property<int>("RestaxinstallmentQty")
                        .HasColumnType("int");

                    b.Property<int>("TaminInstallmentDelay")
                        .HasColumnType("int");

                    b.Property<int>("TaminInstallmentQty")
                        .HasColumnType("int");

                    b.Property<int>("TaminPenaltyVol")
                        .HasColumnType("int");

                    b.Property<int>("TaxInstallmentDelay")
                        .HasColumnType("int");

                    b.Property<int>("TranCommissionQty")
                        .HasColumnType("int");

                    b.Property<int>("TreasuryBillsQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("FinancialMrid");

                    b.ToTable("Financial Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.FinancialSuperMarketMonthlyReport", b =>
                {
                    b.Property<int>("SuperMrid")
                        .HasColumnType("int")
                        .HasColumnName("SuperMRId");

                    b.Property<int>("ActivationQty")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehIssueReqQty")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehRevokeReqQty")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehRevokeVol")
                        .HasColumnType("int");

                    b.Property<int>("AuthenticationQty")
                        .HasColumnType("int");

                    b.Property<int>("CardIssuanceQty")
                        .HasColumnType("int")
                        .HasColumnName("cardIssuanceQty");

                    b.Property<int>("CreaditQty")
                        .HasColumnType("int");

                    b.Property<int>("CreaditVol")
                        .HasColumnType("int");

                    b.Property<int>("CustomersReplyQty")
                        .HasColumnType("int");

                    b.Property<int>("EditQty")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehIssueReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehRevokeReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehRevokeVol")
                        .HasColumnType("int");

                    b.Property<int>("GoharandServatIssueReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GoharandServatRevokeReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GohrandServatIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("GohrandServatRevokeVol")
                        .HasColumnType("int");

                    b.Property<int>("IbshoppRegisterQty")
                        .HasColumnType("int")
                        .HasColumnName("IBshoppRegisterQty");

                    b.Property<int>("InsuranceIssued")
                        .HasColumnType("int");

                    b.Property<int>("InvestorsQty")
                        .HasColumnType("int");

                    b.Property<int>("LegalServQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("OnlineCodeQty")
                        .HasColumnType("int");

                    b.Property<int>("ReportForCustomerC")
                        .HasColumnType("int");

                    b.Property<int>("ReportForCustomerF")
                        .HasColumnType("int");

                    b.Property<int>("TotIsuuVol")
                        .HasColumnType("int");

                    b.Property<int>("TotRevVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcardVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcrowdVol")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SuperMrid");

                    b.ToTable("Financial SuperMarket Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.FixIncomeProperty", b =>
                {
                    b.Property<int>("FixIncomeId")
                        .HasColumnType("int")
                        .HasColumnName("FixIncomeID");

                    b.Property<decimal>("AndookhtehIssue")
                        .HasColumnType("money");

                    b.Property<decimal>("AndookhtehRev")
                        .HasColumnType("money")
                        .HasColumnName("AndookhtehREv");

                    b.Property<int>("BrancheCode")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerQty")
                        .HasColumnType("int");

                    b.Property<decimal>("GanjinehIssue")
                        .HasColumnType("money");

                    b.Property<decimal>("GanjinehRev")
                        .HasColumnType("money");

                    b.Property<int?>("InComeCenterId")
                        .HasColumnType("int")
                        .HasColumnName("InComeCenterID");

                    b.Property<string>("MonthName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MonthNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<decimal>("TotalIssue")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalRev")
                        .HasColumnType("money");

                    b.Property<int>("VirIssueBillQty")
                        .HasColumnType("int");

                    b.Property<decimal>("VirIssueBillVol")
                        .HasColumnType("money");

                    b.HasKey("FixIncomeId");

                    b.HasIndex("BrancheCode");

                    b.HasIndex("InComeCenterId");

                    b.ToTable("FixIncomeProperties");
                });

            modelBuilder.Entity("IBshopDemo.Models.HrMonthlyReport", b =>
                {
                    b.Property<int>("HrmonthlyreportId")
                        .HasColumnType("int")
                        .HasColumnName("HRMonthlyreportID");

                    b.Property<int>("AsuAsgNewPer")
                        .HasColumnType("int");

                    b.Property<int>("BrkFailQty")
                        .HasColumnType("int");

                    b.Property<int>("CoursQty")
                        .HasColumnType("int");

                    b.Property<int>("FloFailQty")
                        .HasColumnType("int");

                    b.Property<int>("Gcissu")
                        .HasColumnType("int")
                        .HasColumnName("GCIssu");

                    b.Property<int>("GurReqFun")
                        .HasColumnType("int");

                    b.Property<int>("GurReqLtt")
                        .HasColumnType("int");

                    b.Property<int>("HrmhiredQty")
                        .HasColumnType("int")
                        .HasColumnName("HRMHiredQty");

                    b.Property<int>("HrpersonnelQty")
                        .HasColumnType("int")
                        .HasColumnName("HRpersonnelQty");

                    b.Property<int>("IntQty")
                        .HasColumnType("int")
                        .HasColumnName("IntQTy");

                    b.Property<int>("LeftQty")
                        .HasColumnType("int");

                    b.Property<int>("LobFailQty")
                        .HasColumnType("int");

                    b.Property<int>("MngRfailQty")
                        .HasColumnType("int")
                        .HasColumnName("MngRFailQty");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("Obqty")
                        .HasColumnType("int")
                        .HasColumnName("OBQty");

                    b.Property<int>("PerEntCnfQty")
                        .HasColumnType("int");

                    b.Property<int>("PntFailQty")
                        .HasColumnType("int");

                    b.Property<int>("PreFailQty")
                        .HasColumnType("int")
                        .HasColumnName("PreFailQTy");

                    b.Property<int>("PyrDedReqLtt")
                        .HasColumnType("int");

                    b.Property<int>("RecLtt")
                        .HasColumnType("int");

                    b.Property<int>("ReplacemntQty")
                        .HasColumnType("int");

                    b.Property<int>("Reqqty")
                        .HasColumnType("int")
                        .HasColumnName("REQQty");

                    b.Property<int>("RrfacFail")
                        .HasColumnType("int")
                        .HasColumnName("RRFAcFail");

                    b.Property<int>("Rrfail")
                        .HasColumnType("int")
                        .HasColumnName("RRFail");

                    b.Property<int>("RsgReq")
                        .HasColumnType("int");

                    b.Property<int>("SendIntLtt")
                        .HasColumnType("int");

                    b.Property<int>("SendOutLtt")
                        .HasColumnType("int");

                    b.Property<int>("SentCvtoDep")
                        .HasColumnType("int")
                        .HasColumnName("SentCVToDep");

                    b.Property<int>("SrvAsgNewPer")
                        .HasColumnType("int");

                    b.Property<int>("StrFailQty")
                        .HasColumnType("int");

                    b.Property<int>("TblFailQty")
                        .HasColumnType("int");

                    b.Property<int>("UsedImp")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("HrmonthlyreportId");

                    b.ToTable("HR Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.IncomeCenter", b =>
                {
                    b.Property<int>("IncomecenterId")
                        .HasColumnType("int")
                        .HasColumnName("IncomecenterID");

                    b.Property<string>("IncomeCenterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncomecenterId");

                    b.ToTable("IncomeCenter", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpicrm", b =>
                {
                    b.Property<int>("Kpicrmcode")
                        .HasColumnType("int")
                        .HasColumnName("KPICRMCode");

                    b.Property<string>("AutAnsPercent")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CallAnsSat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CallAnsSpd")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CallDuration")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Crmiss")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("CRMIss")
                        .IsFixedLength();

                    b.Property<string>("Csat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("CSAT")
                        .IsFixedLength();

                    b.Property<string>("CusReqMetPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CusSat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("DelAvr")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Fcsp")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("FCSP")
                        .IsFixedLength();

                    b.Property<string>("HocallQty")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("HOCallQty")
                        .IsFixedLength();

                    b.Property<string>("IdeCusNeed")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("LeftCallPercent")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MissedCallPercent")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MrkOutcall")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NegFb")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("NegFB")
                        .IsFixedLength();

                    b.Property<string>("NewtooldSat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("newtooldSat")
                        .IsFixedLength();

                    b.Property<string>("OutcallCostAvg")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PerImpPrdSur")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PrdAwaPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("SrvPrdSatPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("TicQty")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("UsersComImpSer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Wtunder3")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("WTUnder3")
                        .IsFixedLength();

                    b.HasKey("Kpicrmcode");

                    b.ToTable("KPICRM", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpidevelopment", b =>
                {
                    b.Property<string>("KpidevelomentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("KPIDevelomentCode")
                        .IsFixedLength();

                    b.Property<string>("AccsugRate")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("ACCSugRate")
                        .IsFixedLength();

                    b.Property<string>("ColRate")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("IdeCusNeed")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("InvSugAvgTime")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NewCusinSrvPrd")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NewTooldsat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PerImpPrdSur")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PrdAwaPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("RdinPrdImp")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("RDinPrdImp")
                        .IsFixedLength();

                    b.Property<string>("SolutionAvgTime")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("SugCap")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("SugInc")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("KpidevelomentCode");

                    b.ToTable("KPIDevelopment", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpifinancial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcrFinRepPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("BillIssueAvgTime")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CnrctrInvoicesMatch")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Cnt")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CtrTimeDuration")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("DemistakeFin")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("DEMistakeFin")
                        .IsFixedLength();

                    b.Property<string>("DevPlnBudPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("FixedAssetConflict")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("fixedAssetConflict")
                        .IsFixedLength();

                    b.Property<string>("IncBudMeetPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("KpifinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("KPIFinCode")
                        .IsFixedLength();

                    b.Property<string>("OdrecintotalRec")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("ODRecintotalRec")
                        .IsFixedLength();

                    b.Property<string>("OtdecLegRe")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("OTDecLegRe")
                        .IsFixedLength();

                    b.Property<string>("RvwAccConflicts")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("RvwInvConflicts")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("KPIFinancial", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpihr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColLoyPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("ColSat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("EduCap")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("EduEfc")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("GenEduCap")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("HrRecDelRat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("IctsrvSat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("ICTSrvSat")
                        .IsFixedLength();

                    b.Property<string>("IntColCam")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("Kpihrcode")
                        .HasColumnType("int")
                        .HasColumnName("KPIHRCode");

                    b.Property<string>("MgmEduCap")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MistakeinPersonalInfo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("OutcallCostAvg")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PapConCap")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("ProEduCap")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("RecDelRat")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("RecEff")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("ReqToNeed")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Sal")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("SalMistakePerc")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("SurveyFeedback")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("TrnColeagPer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("KPIHR", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpimarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrcMrkRti")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("KpimarketingCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("KPIMarketingCode")
                        .IsFixedLength();

                    b.Property<string>("LegMrk")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MrkStgDsg")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NewCusAsset")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NewUser")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("RegistertoIssue")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("SalePlanDsg")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("KPIMarket", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpiplanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivePer")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("DelonPrConf")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("EffImpAct")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("KmsavePercent")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("KMSavePercent")
                        .IsFixedLength();

                    b.Property<string>("KpiplanCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("KPIPlanCode")
                        .IsFixedLength();

                    b.Property<string>("Nps")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("NPS")
                        .IsFixedLength();

                    b.Property<string>("OtimpPercentage")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("OTImpPercentage")
                        .IsFixedLength();

                    b.Property<string>("PrImPercent")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("KPIPlanning", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.MarketingMonthlyReport", b =>
                {
                    b.Property<int>("Mrkmrid")
                        .HasColumnType("int")
                        .HasColumnName("MRKMRId");

                    b.Property<int>("BilboardQty")
                        .HasColumnType("int");

                    b.Property<int?>("BounceRate")
                        .HasColumnType("int");

                    b.Property<int>("ConversationRate")
                        .HasColumnType("int");

                    b.Property<int>("DesignQty")
                        .HasColumnType("int");

                    b.Property<int>("EngQty")
                        .HasColumnType("int");

                    b.Property<int>("GoogleEntTerRate")
                        .HasColumnType("int");

                    b.Property<int>("HoldComptQty")
                        .HasColumnType("int");

                    b.Property<int>("HoldQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcrowdCalllegalCusQty")
                        .HasColumnType("int");

                    b.Property<int>("InsFlwQty")
                        .HasColumnType("int");

                    b.Property<int>("InstFlwQty")
                        .HasColumnType("int");

                    b.Property<int>("KeywordsRank")
                        .HasColumnType("int")
                        .HasColumnName("keywordsRank");

                    b.Property<int>("LinkEntTerRate")
                        .HasColumnType("int");

                    b.Property<int>("LinkdinContentQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("NewsQty")
                        .HasColumnType("int");

                    b.Property<int>("NotifPushQty")
                        .HasColumnType("int");

                    b.Property<int>("PostMediaQty")
                        .HasColumnType("int");

                    b.Property<int>("PrdSrvAdvCallQty")
                        .HasColumnType("int");

                    b.Property<int>("RecVidPostQty")
                        .HasColumnType("int");

                    b.Property<int>("RefEntQty")
                        .HasColumnType("int");

                    b.Property<int>("ReportAdvQty")
                        .HasColumnType("int");

                    b.Property<int>("SentSmsQty")
                        .HasColumnType("int");

                    b.Property<int>("SiteEntMonthlyAvg")
                        .HasColumnType("int");

                    b.Property<int>("SmedEntQty")
                        .HasColumnType("int")
                        .HasColumnName("SMedEntQty");

                    b.Property<int>("SrchEntQty")
                        .HasColumnType("int");

                    b.Property<int>("StateMedAdvQty")
                        .HasColumnType("int");

                    b.Property<int>("SucCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TlgPostContentQty")
                        .HasColumnType("int");

                    b.Property<int>("ToalInvestVol")
                        .HasColumnType("int");

                    b.Property<int>("TrainPostQty")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCntrctQty")
                        .HasColumnType("int");

                    b.Property<int>("VideoQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Mrkmrid");

                    b.ToTable("Marketing Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.MixProperty", b =>
                {
                    b.Property<int>("MixIncomeId")
                        .HasColumnType("int");

                    b.Property<int>("BrancheCode")
                        .HasColumnType("int");

                    b.Property<decimal>("GoharIssue")
                        .HasColumnType("money");

                    b.Property<decimal>("GoharRev")
                        .HasColumnType("money");

                    b.Property<int?>("IncomeCenterId")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ServatIssue")
                        .HasColumnType("money");

                    b.Property<decimal>("ServatRev")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalIssue")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalRev")
                        .HasColumnType("money");

                    b.HasKey("MixIncomeId");

                    b.HasIndex("BrancheCode");

                    b.HasIndex("IncomeCenterId");

                    b.ToTable("MixProperties");
                });

            modelBuilder.Entity("IBshopDemo.Models.OperationKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answeringspeed")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("AppDev")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Cus")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CusAutAsset")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("ErrApp")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("IbCardAutAvgTime")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("OperationKpicode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("OperationKPICode")
                        .IsFixedLength();

                    b.Property<string>("PayToCusAvgTime")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("payToCusAvgTime")
                        .IsFixedLength();

                    b.Property<string>("Piapp")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("PIApp")
                        .IsFixedLength();

                    b.Property<string>("SejAutAvgTime")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("SucOprRate")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("OperationKpi", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.OperationMonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AbCandookhtehBranch")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehBranch");

                    b.Property<decimal?>("AbCandookhtehBranchRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehBranchRE");

                    b.Property<decimal?>("AbCandookhtehOtherBanks")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehOtherBanks");

                    b.Property<decimal?>("AbCandookhtehOtherBanksRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehOtherBanksRE");

                    b.Property<decimal?>("AbCandookhtehSamaneh")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehSamaneh");

                    b.Property<decimal?>("AbCandookhtehSamanehRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehSamanehRE");

                    b.Property<decimal?>("AbCandookhtehSandogh")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehSandogh");

                    b.Property<decimal?>("AbCandookhtehSandoghRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehSandoghRE");

                    b.Property<decimal?>("AbCandookhtehShahr")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehShahr");

                    b.Property<decimal?>("AbCandookhtehShahrRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehShahrRE");

                    b.Property<decimal?>("AbCandookhtehShahrnet")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehShahrnet");

                    b.Property<decimal?>("AbCandookhtehShahrnetRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehShahrnetRE");

                    b.Property<decimal?>("AbCandookhtehTamaddon")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehTamaddon");

                    b.Property<decimal?>("AbCandookhtehTamaddonRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehTamaddonRE");

                    b.Property<decimal?>("AbCandookhtehTotal")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehTotal");

                    b.Property<decimal?>("AbCandookhtehTotalRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCAndookhtehTotalRE");

                    b.Property<decimal?>("AbCganjinehBranches")
                        .HasColumnType("money");

                    b.Property<decimal?>("AbCganjinehBranchesRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCganjinehBranchesRE");

                    b.Property<decimal?>("AbCganjinehSamaneh")
                        .HasColumnType("money");

                    b.Property<decimal?>("AbCganjinehSamanehRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCganjinehSamanehRE");

                    b.Property<decimal?>("AbCganjinehSandogh")
                        .HasColumnType("money");

                    b.Property<decimal?>("AbCganjinehSandoghRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCganjinehSandoghRE");

                    b.Property<decimal?>("AbCganjinehShahr")
                        .HasColumnType("money");

                    b.Property<decimal?>("AbCganjinehShahrRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCganjinehShahrRE");

                    b.Property<decimal?>("AbCganjinehShahrnet")
                        .HasColumnType("money");

                    b.Property<decimal?>("AbCganjinehShahrnetRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCganjinehShahrnetRE");

                    b.Property<decimal?>("AbCganjinehTamaddon")
                        .HasColumnType("money")
                        .HasColumnName("AbCGanjinehTamaddon");

                    b.Property<decimal?>("AbCganjinehTamaddonRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCGanjinehTamaddonRE");

                    b.Property<decimal?>("AbCganjinehTotal")
                        .HasColumnType("money");

                    b.Property<decimal?>("AbCganjinehTotalRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCganjinehTotalRE");

                    b.Property<decimal?>("AbCgoharBranch")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharBranch");

                    b.Property<decimal?>("AbCgoharBranchRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharBranchRE");

                    b.Property<decimal?>("AbCgoharSamaneh")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharSamaneh");

                    b.Property<decimal?>("AbCgoharSamanehRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharSamanehRE");

                    b.Property<decimal?>("AbCgoharSandogh")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharSandogh");

                    b.Property<decimal?>("AbCgoharSandoghRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharSandoghRE");

                    b.Property<decimal?>("AbCgoharTamaddon")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharTamaddon");

                    b.Property<decimal?>("AbCgoharTamaddonRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharTamaddonRE");

                    b.Property<decimal?>("AbCgoharTotal")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharTotal");

                    b.Property<decimal?>("AbCgoharTotalRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCGoharTotalRE");

                    b.Property<decimal?>("AbCservatBranch")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatBranch");

                    b.Property<decimal?>("AbCservatBranchRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatBranchRE");

                    b.Property<decimal?>("AbCservatSamaneh")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatSamaneh");

                    b.Property<decimal?>("AbCservatSamanehRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatSamanehRE");

                    b.Property<decimal?>("AbCservatSandogh")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatSandogh");

                    b.Property<decimal?>("AbCservatSandoghRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatSandoghRE");

                    b.Property<decimal?>("AbCservatTamaddon")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatTamaddon");

                    b.Property<decimal?>("AbCservatTamaddonRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatTamaddonRE");

                    b.Property<decimal?>("AbCservatTotal")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatTotal");

                    b.Property<decimal?>("AbCservatTotalRe")
                        .HasColumnType("money")
                        .HasColumnName("AbCServatTotalRE");

                    b.Property<int>("BillConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("BkgCrdQty")
                        .HasColumnType("int");

                    b.Property<int>("BkgCrdVol")
                        .HasColumnType("int");

                    b.Property<int>("BkgNewCustomer")
                        .HasColumnType("int");

                    b.Property<int>("BkgReqCnfqty")
                        .HasColumnType("int")
                        .HasColumnName("BkgReqCNFQty");

                    b.Property<int>("BranchInternetConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("FixedConflictQty")
                        .HasColumnType("int");

                    b.Property<int>("IntternetEntranceConflictReq")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("MonthNumber")
                        .HasColumnType("int")
                        .HasColumnName("Month Number");

                    b.Property<int>("Oprmrid")
                        .HasColumnType("int")
                        .HasColumnName("OPRMRId");

                    b.Property<int>("PoseConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("RemotChcAut")
                        .HasColumnType("int");

                    b.Property<int>("SmsinternetConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalChcSejam")
                        .HasColumnType("int");

                    b.Property<int>("TotalConflictsProcess")
                        .HasColumnType("int");

                    b.Property<int>("TotalEditAcc")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcardIssuesQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcardIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalIdeEdit")
                        .HasColumnType("int");

                    b.Property<int>("TotalIssuCrt")
                        .HasColumnType("int");

                    b.Property<int>("TotalLegAut")
                        .HasColumnType("int");

                    b.Property<int>("TotalTransferVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalmsgQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Operation Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.ProcessDesignMonthlyReport", b =>
                {
                    b.Property<int>("ProcessDesignMrid")
                        .HasColumnType("int")
                        .HasColumnName("ProcessDesignMRId");

                    b.Property<int>("AsmPrc")
                        .HasColumnType("int");

                    b.Property<int>("CrmcommHold")
                        .HasColumnType("int")
                        .HasColumnName("CRMCommHold");

                    b.Property<int>("CrmdoneCmm")
                        .HasColumnType("int")
                        .HasColumnName("CRMDoneCmm");

                    b.Property<int>("CrmfailCmm")
                        .HasColumnType("int")
                        .HasColumnName("CRMFailCmm");

                    b.Property<int>("DevCommHold")
                        .HasColumnType("int");

                    b.Property<int>("DevDoneCmm")
                        .HasColumnType("int");

                    b.Property<int>("DevFailCmm")
                        .HasColumnType("int");

                    b.Property<int>("DlgQty")
                        .HasColumnType("int");

                    b.Property<int>("FormQty")
                        .HasColumnType("int");

                    b.Property<int>("IndexQty")
                        .HasColumnType("int");

                    b.Property<int>("InsQty")
                        .HasColumnType("int");

                    b.Property<int>("KpimonitoringQty")
                        .HasColumnType("int")
                        .HasColumnName("KPIMonitoringQty");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MrkDoneCmm")
                        .HasColumnType("int")
                        .HasColumnName("MRkDoneCmm");

                    b.Property<int>("MrkFailCmm")
                        .HasColumnType("int")
                        .HasColumnName("MRkFailCmm");

                    b.Property<int>("MrkcommHold")
                        .HasColumnType("int")
                        .HasColumnName("MRKCommHold");

                    b.Property<int>("PrcDesign")
                        .HasColumnType("int");

                    b.Property<int>("PrcdQty")
                        .HasColumnType("int");

                    b.Property<int>("RegQty")
                        .HasColumnType("int");

                    b.Property<int>("RelInsQty")
                        .HasColumnType("int");

                    b.Property<int>("RelPrcdQty")
                        .HasColumnType("int");

                    b.Property<int>("RelReqQty")
                        .HasColumnType("int");

                    b.Property<int>("ReviewPrc")
                        .HasColumnType("int");

                    b.Property<int>("ReviwIndxQty")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProcessDesignMrid");

                    b.ToTable("ProcessDesignMonthlyReport", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Product", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int")
                        .HasColumnName("ProductsID");

                    b.Property<int>("BrancheCode")
                        .HasColumnType("int");

                    b.Property<int>("CardQty")
                        .HasColumnType("int");

                    b.Property<decimal>("DealValue")
                        .HasColumnType("money");

                    b.Property<int>("IbcardIssueQty")
                        .HasColumnType("int");

                    b.Property<decimal>("IbcrowdVol")
                        .HasColumnType("money");

                    b.Property<decimal>("Income")
                        .HasColumnType("money");

                    b.Property<int?>("IncomeCenterId")
                        .HasColumnType("int");

                    b.Property<int>("KargozariBoursCode")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("MonthNumber")
                        .HasColumnType("int");

                    b.HasKey("ProductsId");

                    b.HasIndex("BrancheCode");

                    b.HasIndex("IncomeCenterId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IBshopDemo.Models.ProductDevelopmentMontylyReport", b =>
                {
                    b.Property<int>("DevMrid")
                        .HasColumnType("int")
                        .HasColumnName("DevMRId");

                    b.Property<int>("AcceptedSuggestQty")
                        .HasColumnType("int");

                    b.Property<int>("CheckedSuggestQty")
                        .HasColumnType("int");

                    b.Property<int>("EconomicalSuggestQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcComplQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcCreadiCardReqQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcCreaditCardCustQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcCreaditCardProcessAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("IbwDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("IbwDesignTime")
                        .HasColumnType("int");

                    b.Property<int>("IbwDesignVol")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("SuggestPersonnelQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DevMrid");

                    b.ToTable("Product Development Montyly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.QaMonthlyReport", b =>
                {
                    b.Property<int>("Qamrid")
                        .HasColumnType("int")
                        .HasColumnName("QAMRId");

                    b.Property<int>("AgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("AGradeQty");

                    b.Property<int>("ApgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("APGradeQty");

                    b.Property<int>("BgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("BGradeQty");

                    b.Property<int>("CalMgtIncQty")
                        .HasColumnType("int");

                    b.Property<int>("CalMgtOutQty")
                        .HasColumnType("int");

                    b.Property<int>("CalMgtPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("CalMgtPerOutQty")
                        .HasColumnType("int");

                    b.Property<int>("CgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("CGradeQty");

                    b.Property<int>("DgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("DGradeQty");

                    b.Property<int>("EgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("EGradeQty");

                    b.Property<int>("FgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("FGradeQty");

                    b.Property<int>("GgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("GGradeQty");

                    b.Property<int>("HgradeQty")
                        .HasColumnType("int")
                        .HasColumnName("HGradeQty");

                    b.Property<int>("KnwFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("KnwFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int")
                        .HasColumnName("Month_Number");

                    b.Property<int>("ProFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailOutQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailPerChatQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailPerOutQty")
                        .HasColumnType("int");

                    b.Property<int?>("RepFail")
                        .HasColumnType("int");

                    b.Property<int>("SurFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailOutQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailPerChatQty")
                        .HasColumnType("int")
                        .HasColumnName("SurFailPerCHAtQty");

                    b.Property<int>("SurFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailPerOutQty")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyChatOnline")
                        .HasColumnType("int");

                    b.Property<int>("SysFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("SysFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailOutQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailPerChatQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailPerOutQty")
                        .HasColumnType("int");

                    b.Property<int>("TimFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("TimFailPerChatQty")
                        .HasColumnType("int");

                    b.Property<int>("ToalOnlineChat")
                        .HasColumnType("int");

                    b.Property<int>("TotalChcIncCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalChcOutCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalCheckedOnlineChat")
                        .HasColumnType("int");

                    b.Property<int>("TotalPersonnelIncCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalPersonnelOutCallQty")
                        .HasColumnType("int");

                    b.Property<int>("WelFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("WelFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Qamrid");

                    b.ToTable("QA Monthly Report", (string)null);
                });

            modelBuilder.Entity("IBshopDemo.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("IBshopDemo.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IBshopDemo.Models.FixIncomeProperty", b =>
                {
                    b.HasOne("IBshopDemo.Models.BranchesInfo", "BrancheCodeNavigation")
                        .WithMany("FixIncomeProperties")
                        .HasForeignKey("BrancheCode")
                        .IsRequired()
                        .HasConstraintName("FK_FixIncomeProperties_Branches Info");

                    b.HasOne("IBshopDemo.Models.IncomeCenter", "InComeCenter")
                        .WithMany("FixIncomeProperties")
                        .HasForeignKey("InComeCenterId")
                        .HasConstraintName("FK_FixIncomeProperties_IncomeCenter");

                    b.Navigation("BrancheCodeNavigation");

                    b.Navigation("InComeCenter");
                });

            modelBuilder.Entity("IBshopDemo.Models.MixProperty", b =>
                {
                    b.HasOne("IBshopDemo.Models.BranchesInfo", "BrancheCodeNavigation")
                        .WithMany("MixProperties")
                        .HasForeignKey("BrancheCode")
                        .IsRequired()
                        .HasConstraintName("FK_MixProperties_Branches Info");

                    b.HasOne("IBshopDemo.Models.IncomeCenter", "IncomeCenter")
                        .WithMany("MixProperties")
                        .HasForeignKey("IncomeCenterId")
                        .HasConstraintName("FK_MixProperties_MixProperties");

                    b.Navigation("BrancheCodeNavigation");

                    b.Navigation("IncomeCenter");
                });

            modelBuilder.Entity("IBshopDemo.Models.Product", b =>
                {
                    b.HasOne("IBshopDemo.Models.BranchesInfo", "BrancheCodeNavigation")
                        .WithMany("Products")
                        .HasForeignKey("BrancheCode")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Branches Info");

                    b.HasOne("IBshopDemo.Models.IncomeCenter", "IncomeCenter")
                        .WithMany("Products")
                        .HasForeignKey("IncomeCenterId")
                        .HasConstraintName("FK_Products_Products");

                    b.Navigation("BrancheCodeNavigation");

                    b.Navigation("IncomeCenter");
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchesInfo", b =>
                {
                    b.Navigation("FixIncomeProperties");

                    b.Navigation("MixProperties");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("IBshopDemo.Models.IncomeCenter", b =>
                {
                    b.Navigation("FixIncomeProperties");

                    b.Navigation("MixProperties");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
